# Concepts of tensors using TensorFlow

* Introduction to Tensors
* Getting information from tensors
* Manipulating Tensors
* Tensors and NumPy
* Using @tf.function
* Using GPUs with TensorFlow

## Introduction to Tensors

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [ ]:
# Creating tensors with tf.constant()
scalar = tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check number of dimensions of a tensor (ndim)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of Vector
vector.ndim

1

In [ ]:
# Create a Matrix (Matrix has more than one dimension)
matrix = tf.constant([[10,7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix 
another_matrix= tf.constant([[10.,7.],
                            [3.,2.],
                             [8.,9.]], dtype=tf.float16) # Specify datatype with dtype parameter
another_matrix                             

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# What is the number of dimensions of another_matrix
another_matrix.ndim

2

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3,],
                      [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

* Scalar : A single number
* Vector : A Number with direction (Wind speed and direction)
* Matrix : A 2-dimensional array of numbers
* Tensor : An n- dimensional array of numbers (where n can be any number, 1 dimensional tensor is a vector)


Creating Tensors with tf.Variable



In [ ]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unChangeable_tensor = tf.constant([10,7])

changeable_tensor, unChangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Changing elements in Changeable Tensor
changeable_tensor[0] = 7
changeable_tensor


TypeError: ignored

In [ ]:
# .assign
changeable_tensor[0].assign(7)
changeable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Changing unchangeable tensor
unChangeable_tensor[0].assign(7)
unChangeable_tensor


AttributeError: ignored

### Creating Random Tensors

## Random tensors are tensors of some arbitrary 