<a href="https://colab.research.google.com/github/GuruPrasadhBM/TF_Practice/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Concepts of tensors using TensorFlow

* Introduction to Tensors
* Getting information from tensors
* Manipulating Tensors
* Tensors and NumPy
* Using @tf.function
* Using GPUs with TensorFlow

## Introduction to Tensors

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [3]:
# Creating tensors with tf.constant()
scalar = tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [4]:
# Check number of dimensions of a tensor (ndim)
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Check the dimension of Vector
vector.ndim

1

In [7]:
# Create a Matrix (Matrix has more than one dimension)
matrix = tf.constant([[10,7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
# Create another matrix 
another_matrix= tf.constant([[10.,7.],
                            [3.,2.],
                             [8.,9.]], dtype=tf.float16) # Specify datatype with dtype parameter
another_matrix                             

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
# What is the number of dimensions of another_matrix
another_matrix.ndim

2

In [11]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3,],
                      [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

* Scalar : A single number
* Vector : A Number with direction (Wind speed and direction)
* Matrix : A 2-dimensional array of numbers
* Tensor : An n- dimensional array of numbers (where n can be any number, 1 dimensional tensor is a vector)


Creating Tensors with tf.Variable



In [13]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unChangeable_tensor = tf.constant([10,7])

changeable_tensor, unChangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# Changing elements in Changeable Tensor
changeable_tensor[0] = 7
changeable_tensor


TypeError: ignored

In [15]:
# .assign
changeable_tensor[0].assign(7)
changeable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
# Changing unchangeable tensor
unChangeable_tensor[0].assign(7)
unChangeable_tensor


AttributeError: ignored

### Creating Random Tensors

 Random tensors are tensors of some arbitrary size which contains random numbers

In [20]:
# Create two random tensors

random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape = (3 , 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))

# Are they equal

random_1, random_1, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

#### Uniform Distribution
A distribution that has constant probability

### Shuffle the order of elements in a tensor

In [30]:
not_shuffled = tf.constant([[10,7],
                           [3,2],
                           [8,9]])
print(not_shuffled.ndim)
print(not_shuffled)

# Shuffle the non shuffled tensor
tf.random.shuffle(not_shuffled, seed=5)

2
tf.Tensor(
[[10  7]
 [ 3  2]
 [ 8  9]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  2],
       [ 8,  9],
       [10,  7]], dtype=int32)>

### Random Seed Generation

In [31]:
not_shuffled1 = tf.constant([[9,8], [8,6], [5,4]])

In [32]:
tf.random.set_seed(25)